{% set name = "regressio" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/regressio-{{ version }}.tar.gz
  sha256: eea3c778dc7f1db582a19ee1f08ce95247d73292d442104c71ceab8fd334801c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - matplotlib-base
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - regressio
  commands:
    - pip check
    # Skip tests for win due to np.float128 not being implemented in win
    - pytest -vvv --capture=tee-sys tests  # [not win]
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/brendanartley/regressio
  summary: A python module for regression, interpolation and smoothing.
  license: MIT
  license_file: License

extra:
  recipe-maintainers:
    - thewchan
